export default {
  ddUrlInspector: {
    tab: "URL'er & omdirigeringer",
    currentUrls: "Aktuelle URL'er",
    incoming: 'Omdirigeringer til denne side',
    outgoing: 'Udgående omdirigering',
    canonical: 'Canonical',
    none: 'Ingen',
    noUrl: 'Denne side har ingen URL (er den udgivet?)',
    cultureNotPublished: 'Ingen URL for dette sprog (ikke udgivet?)',
    copy: 'Kopiér',
    test: 'Test',
    open: 'Åbn',
    copyRedirects: 'Kopiér omdirigeringer',
    copied: 'Kopieret til udklipsholderen',
    copyFailed: 'Kunne ikke kopiere til udklipsholderen',
    testResult: 'Svar',
    notAllowed: 'Denne URL kan ikke testes',
    privateAddress: 'Denne adresse ligger på et internt netværk og kan ikke testes',
    noBaseUrl: 'Denne URL kan ikke testes, fordi sidens basis-URL er ukendt',
    invalidUrl: 'Dette er ikke en gyldig URL',
    requestFailed: 'Forespørgslen mislykkedes',
    timedOut: 'Forespørgslen fik timeout',
    cancelled: 'Forespørgslen blev annulleret',
    testing: 'Tester…',
    failed: 'URL-oplysningerne kunne ikke indlæses.',
  },
};
