export default {
  ddUrlInspector: {
    tab: 'URLs & Weiterleitungen',
    currentUrls: 'Aktuelle URLs',
    incoming: 'Weiterleitungen auf diese Seite',
    outgoing: 'Ausgehende Weiterleitung',
    canonical: 'Canonical',
    none: 'Keine',
    noUrl: 'Diese Seite hat keine URL (ist sie veröffentlicht?)',
    cultureNotPublished: 'Keine URL für diese Sprache (nicht veröffentlicht?)',
    copy: 'Kopieren',
    test: 'Testen',
    open: 'Öffnen',
    copyRedirects: 'Weiterleitungen kopieren',
    copied: 'In die Zwischenablage kopiert',
    copyFailed: 'Kopieren in die Zwischenablage fehlgeschlagen',
    testResult: 'Antwort',
    notAllowed: 'Diese URL kann nicht getestet werden',
    privateAddress: 'Diese Adresse liegt in einem internen Netzwerk und kann nicht getestet werden',
    noBaseUrl: 'Diese URL kann nicht getestet werden, weil die Basis-URL der Website unbekannt ist',
    invalidUrl: 'Dies ist keine gültige URL',
    requestFailed: 'Die Anfrage ist fehlgeschlagen',
    timedOut: 'Zeitüberschreitung bei der Anfrage',
    cancelled: 'Die Anfrage wurde abgebrochen',
    testing: 'Wird getestet…',
    failed: 'URL-Informationen konnten nicht geladen werden.',
  },
};
