export default {
  ddUrlInspector: {
    tab: 'URLs & Redirects',
    currentUrls: 'Current URLs',
    incoming: 'Redirects to this page',
    outgoing: 'Outgoing redirect',
    canonical: 'Canonical',
    none: 'None',
    noUrl: 'This page has no URL (is it published?)',
    cultureNotPublished: 'No URL for this language (not published?)',
    copy: 'Copy',
    test: 'Test',
    open: 'Open',
    copyRedirects: 'Copy redirects',
    copied: 'Copied to clipboard',
    copyFailed: 'Could not copy to clipboard',
    testResult: 'Response',
    notAllowed: 'This URL cannot be tested',
    noBaseUrl: 'This URL cannot be tested because the site base URL is unknown',
    invalidUrl: 'This is not a valid URL',
    requestFailed: 'The request failed',
    timedOut: 'The request timed out',
    cancelled: 'The request was cancelled',
    testing: 'Testing…',
    failed: 'Could not load URL information.',
  },
};
