export default {
  ddUrlInspector: {
    tab: 'URL et redirections',
    currentUrls: 'URL actuelles',
    incoming: 'Redirections vers cette page',
    outgoing: 'Redirection sortante',
    canonical: 'Canonique',
    none: 'Aucune',
    noUrl: "Cette page n'a pas d'URL (est-elle publiée ?)",
    cultureNotPublished: 'Aucune URL pour cette langue (non publiée ?)',
    copy: 'Copier',
    test: 'Tester',
    open: 'Ouvrir',
    copyRedirects: 'Copier les redirections',
    copied: 'Copié dans le presse-papiers',
    copyFailed: 'Impossible de copier dans le presse-papiers',
    testResult: 'Réponse',
    notAllowed: 'Cette URL ne peut pas être testée',
    privateAddress: 'Cette adresse se trouve sur un réseau interne et ne peut pas être testée',
    noBaseUrl: "Cette URL ne peut pas être testée car l'URL de base du site est inconnue",
    invalidUrl: "Ce n'est pas une URL valide",
    requestFailed: 'La requête a échoué',
    timedOut: 'La requête a expiré',
    cancelled: 'La requête a été annulée',
    testing: 'Test en cours…',
    failed: "Impossible de charger les informations d'URL.",
  },
};
