export default {
  ddUrlInspector: {
    tab: "URL's & Redirects",
    currentUrls: "Huidige URL's",
    incoming: 'Redirects naar deze pagina',
    outgoing: 'Uitgaande redirect',
    canonical: 'Canonical',
    none: 'Geen',
    noUrl: 'Deze pagina heeft geen URL (is hij gepubliceerd?)',
    cultureNotPublished: 'Geen URL voor deze taal (niet gepubliceerd?)',
    copy: 'Kopieer',
    test: 'Test',
    open: 'Open',
    copyRedirects: 'Kopieer redirects',
    copied: 'Gekopieerd naar klembord',
    copyFailed: 'Kopiëren naar klembord is mislukt',
    testResult: 'Antwoord',
    notAllowed: 'Deze URL kan niet worden getest',
    noBaseUrl: 'Deze URL kan niet worden getest omdat de basis-URL van de site onbekend is',
    invalidUrl: 'Dit is geen geldige URL',
    requestFailed: 'Het verzoek is mislukt',
    timedOut: 'Het verzoek is verlopen',
    cancelled: 'Het verzoek is geannuleerd',
    testing: 'Testen…',
    failed: 'URL-informatie kon niet worden geladen.',
  },
};
