<Project>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Authors>DynamicDave</Authors>
    <Company>DynamicDave</Company>
    <Copyright>Copyright (c) DynamicDave</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>0.2.0</Version>
  </PropertyGroup>
</Project>
