// This file is auto-generated by @hey-api/openapi-ts

export { type Options, UrlInspectorService } from './sdk.gen';
export type { ClientOptions, GetUrlInspectorData, GetUrlInspectorErrors, GetUrlInspectorResponse, GetUrlInspectorResponses, RedirectEntry, TestUrlData, TestUrlErrors, TestUrlRequest, TestUrlResponse, TestUrlResponse2, TestUrlResponses, UrlEntry, UrlInspectorResponse } from './types.gen';
